apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: default
  name: 'http-echo'
spec:
  selector:
    matchLabels:
      app: http-echo
  replicas: 1
  template:
    metadata:
      labels:
        app: http-echo
    spec:
      # runtimeClassName: kata
      containers:
        - name: http-container
          image: >-
            quay.io/eesposit/http-echo-ema:latest
          ports:
            - containerPort: 8080
              protocol: TCP
          env:
            - name: HOSTNAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: KATACLASS
              value: kata
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%