apiVersion: apps/v1
kind: Deployment
metadata:
  name: on-prem-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: my-web-app
  template:
    metadata:
      labels:
        app: my-web-app
    spec:
      containers:
      - name: my-web-app
        image: quay.io/eesposit/http-echo-ema:latest
        resources:
          request:
            memory: "1Gi"
          limits:
            memory: "1Gi"
        env:
        - name: HOSTNAME
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: metadata.name
        - name: MEMORY_LIMITS
          valueFrom:
            resourceFieldRef:
              containerName: my-web-app
              resource: limits.memory
        - name: DD_MB_SIZE
          value: "100"
        # - name: MAX_MEMORY_STRESS_PERC
          # value: "80"
        ports:
        - containerPort: 8080
        securityContext:
            privileged: true