apiVersion: v1
kind: Pod
metadata:
  name: example
  labels:
    app: httpd
  namespace: default
spec:
  securityContext:
    seccompProfile:
      type: RuntimeDefault
  containers:
    - name: httpd
      image: 'quay.io/eesposit/http-echo-ema:latest'
      imagePullPolicy: Always
      resources:
        request:
          memory: "1Gi"
        limits:
          memory: "1Gi"
      env:
        - name: HOSTNAME
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: metadata.name
        - name: ATTESTATION
          value: "0"
        - name: DD_MB_SIZE
          value: "100"
        - name: SLEEP_SEC
          value: "0"
      ports:
        - containerPort: 8080
      securityContext:
        privileged: true
